name: Hola mundo

on:
 workflow_dispatch:

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: decir-hola
        hecho: "Hola a todos"

      - name: decir-fecha
        hecho: date
        
