name: Hello world with workflow
on: 
  workflow_dispatch: 

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World"

      - name: Fecha de Hoy
        run: date
        
      - name: Listar archivos ocultos
        run: ls -a

      - name: Nombre
        run: echo "César Abraham Lopez Aguilar"
