name: Fecha del Sistema

on:
  workflow_dispatch: 

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Saludar
        run: echo "Buenvenidos a todos"
   Tarea2:
     runs-on: ubuntu-latest
     steps:
      - name: Fecha
        run: echo "Hoy es $(date)"
